BRING-17: Implement ComponentAnnotationScanner
Blyznytsia/bring pull request #28
Opened 2022-07-20 17:42 UTC by withgodinheart

# Why:
It allows us to find the beans to put in the ApplicationContext

# How:
1. Scan provided package
2. Find all classes annotated with Component annotation
3. Create BeanDefinition based on these classes
4. If the class has fields annotated with Autowired annotation, then add dependencies to BeanDefinition#dependsOnBeans
5. Return Collection of BeanDefinition

# Testing:
Test data is taken from org.blyznytsia.scanner.data test package

<img width="820" alt="Screenshot 2022-07-20 at 1 33 43 PM" src="https://user-images.githubusercontent.com/20487669/180046215-f543e24f-6052-4e14-913f-dc5cb1f305a1.png">

2022-07-20 18:03 UTC, withgodinheart commented on src/main/java/org/blyznytsia/scanner/ComponentAnnotationScanner.java
> +                .filter(el -> el.getType().isAnnotationPresent(COMPONENT_ANNOTATION))
I think I should delete this line

2022-07-20 19:48 UTC, kebann requested changes

2022-07-20 19:48 UTC, kebann commented on src/test/java/org/blyznytsia/scanner/ComponentAnnotationScannerTest.java
> +    }
can be refactored to be as follows to take advantage of AssertJ API

``` java
        var beanDefinitions =
                new ComponentAnnotationScanner().scan(PACKAGE_NAME);

        assertThat(beanDefinitions)
                .map(BeanDefinition::getName)
                // the size check is included
                .containsOnly(SERVICE2_NAME, SERVICE1_NAME);

        var service1 = getBeanDefinitionByName(beanDefinitions, SERVICE1_NAME);
        var service2 = getBeanDefinitionByName(beanDefinitions, SERVICE2_NAME);

        assertThat(service1.getDependsOnBeans()).isEmpty();
        assertThat(service2.getDependsOnBeans())
                .hasSize(SERVICE2_DEPENDENCIES_SIZE)
                .first()
                .isEqualTo(SERVICE2_DEPENDENCY_NAME);
```

2022-07-20 19:48 UTC, kebann commented on src/test/java/org/blyznytsia/scanner/ComponentAnnotationScannerTest.java
> +    void scan_givenValidPackage_shouldReturnValidBeanDefinitionsList() {
We can discuss the test naming convention on a daily call and stick to it to keep things consistent.

IMO, `shouldReturnValidBeanDefinitionsAfterScanning` should suffice and more details should be provided via `@DisplayName`

2022-07-21 03:40 UTC, kebann commented on src/test/java/org/blyznytsia/scanner/ComponentAnnotationScannerTest.java
> +    void scan_givenValidPackage_shouldReturnValidBeanDefinitionsList() {
agreed

2022-07-21 11:25 UTC, PavloChechehov commented on src/test/java/org/blyznytsia/scanner/ComponentAnnotationScannerTest.java
> +        final var service1 = getBeanDefinitionByName(beanDefinitions, SERVICE1_NAME);
I suppose we no need to overuse the `final` word, except in the case where it is vital

2022-07-21 17:58 UTC, merged