Code Style
Blyznytsia/bring pull request #33
Opened 2022-07-23 14:55 UTC by DenisKulpa

# Why:

Reformats Java source code to comply with Google Java Style

# How:

Look code_style.md file

2022-07-23 19:24 UTC, kebann commented
add a proper commit message instead of `For example reformat main.class and autowired.class with java-google-

2022-07-23 19:25 UTC, kebann requested changes
add maven spotless plugin in the scope of this task

2022-07-25 12:52 UTC, PavloChechehov approved these changes

2022-07-25 23:35 UTC, kebann approved these changes

2022-07-26 10:20 UTC, amfibiotik approved these changes

2022-07-26 18:25 UTC, merged